project:
  type: website

website:
  title: "Presentations"
  page-navigation: true
  page-footer:
      center: 
        - text: "Last updated: {{< now >}}"
  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: github
        menu:
          - text: Report an issue
            href:  https://github.com/EricMFink/Presentations/issues/new
          - text: View source code
            href:  https://github.com/Presentations
    collapse-level: 2
    contents: 
      - href: index.qmd
        text: Home
      - section: Contents
        contents:
        - text: Attorney Advertising
          href: presentations/attorney-advertising.qmd
        - text: Law Student Residents, Interns, & Law Clerks
          href: law-student-employment.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: revealjs-styles.css
    title-block-style: none
    reference-location: margin
    citation-location: margin
    toc: false
    number-sections: false
    include-in-header:
    - text: |
        <link rel="stylesheet" href="https://use.typekit.net/viv2jun.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Literata:ital,opsz,wght@0,7..72,200..900;1,7..72,200..900&family=Noto+Sans+JP:wght@100..900&display=swap" rel="stylesheet">
        <link rel="shortcut icon" href="https://www.emfink.net/assets/img/favicon.ico">
        <meta name="robots" content="noarchive">