---

title: 'Know Your Rights:'
subtitle: "Police Encounters"
author: Eric M. Fink 
affiliation: Elon Law School 
date: 18 July 2024

format:
  metropolis-revealjs: 
    controls: false
    navigation-mode: vertical
    slide-level: 4
	output-file: kyr-police-revealjs.html
---

## Disclaimer 

This is a general overview of issues that may arise in police encounters. The information presented is not offered or intended as legal advice.

## Police Encounters & Arrests 

### Police Questioning 

In general, a police officer may lawfully ask you questions at any time, without having to demonstrate reasonable suspicion or probable cause. 

- If you speak to a law enforcement officer, your statements may be used against you and others. 
- It is a criminal offense to provide false information to a police officer.

### Constitutional Rights When Questioned by Police 

You have a right to refuse to answer police questions, and the right to consult with a lawyer before agreeing to speak to the police. These rights apply whether or not you have been detained or arrested. 

### Miranda Warning

The police are not required to inform you of those rights unless they intend to conduct a custodial interrogation (i.e. question you while under arrest or otherwise not free to go). 

### Right to Remain Silent 

You are not required to tell the police that you are exercising your right to remain silent.

- It is usually a good idea to do so. 
- Even if you answer some questions, you may still stop and refuse to answer any further questions until you have a lawyer.
- You may not lawfully be arrested or punished for failing or refusing to answer police questions.

### Right to Counsel 

Police officers may try to pressure or persuade you to speak to them without a consulting a lawyer. 

- Bear in mind that the police are legally permitted to lie to you. 

### Common Police Tactics

Police officers may threaten you with a grand jury subpoena.

- They may be bluffing
- Even if they’re not, you are entitled to consult with a lawyer before testifying.

### Common Police Tactics

Police officers may promise leniency in criminal charges or sentencing.

- Criminal charges and plea bargains are up to the prosecutor, not the police.

## Police Stops & Detention 

If you are stopped by a police officer, you are legally entitled to walk away unless you have been detained or arrested. If you’re unsure, you can ask if you are free to go. 

### Police Stops

It is generally a good idea to walk away calmly. 

- If you run, or otherwise act in a “furtive” “suspicious” manner, the officer might use that as a pretext to detain or arrest you. 

### Police Stops

It is generally not a good idea to argue with or insult the officer.

- Even though your statements may be protected under the 1st Amendment, the officer is unlikely to be persuaded and is likely to react by detaining or arresting you.  

### Detention 

Detention means that you have been stopped by a police officer and are not free to go.

- Detention may lead to an arrest, but it is not the same thing.

### Detention: Constitutional Rights 

If you are detained, your constitutional rights (including the right to remain silent) apply, but the police are not required to inform you of those rights unless you are arrested. 

### Pat-Downs

If you are detained, the officer may conduct a “pat down” (an external check) for weapons.

### Reasonable Suspicion

Legally, a police officer is required to have “reasonable suspicion” that you are armed and dangerous before conducting a pat down. 

- Police often cite “furtive” or “suspicious” movements or demeanor to justify a pat down. 

### Searches 

If you are detained but not arrested, the officer may not lawfully conduct any search beyond a pat-down (e.g. inside your pockets, under your clothing, inside a bag or other item) without your consent or “probable cause”. 

### Consent to Search 

You may tell a police officer you do not consent to a search. 

- Refusal to consent is not probable cause for a search. 
- If the officer proceeds (which is likely), you do not have a legal right to physically resist. 

### Probable Cause 

Probable cause means that the officer has knowledge of facts sufficient to support a reasonable belief that you are engaged in criminal activity or have evidence of a crime in your possession. 

## Arrests 

Arrests, like searches, require probable cause. 

### Notice of Arrest 

Police officers will usually tell you if you are being placed under arrest. 

- If you are unsure, you may ask. 
- The officer will not necessarily inform you of the charges at the time of arrest. 

### Resisting Arrest 

Resisting arrest is a crime, even if the arrest itself is unlawful or the police use excessive force in carrying out the arrest. 

### Search Incident to Arrest 

Once you have been placed under arrest, the police may lawfully conduct a search: 

- Inside your clothing and any objects you are holding or carrying. 
- The area within your immediate control.

### Miranda Warning 

If you are arrested, the police may not lawfully interrogate you without advising you of your right to refuse to answer questions and your right to legal representation. 

The police may recite the _Miranda_ warning at the time of arrest or at a later time prior to any interrogation. 

## Rights Following Arrest 

### Phone Call 

You have the right to make a phone call within a reasonable time after being arrested. 

### Surveillance of Phone Calls

The police may not listen to your calls with your lawyer. 

But they may (and mostly likely will) listen to any other calls. 

### Court Appearance

You have the right to appear before a judge or magistrate within a reasonable time after being arrested (usually within 48 hours). 

### Arraignment

The purpose of this appearance is to hear the formal charges against you, decide on bail, and enter a plea. 

### Legal Representation

You have a right to be represented by a lawyer at an arraignment and all other court appearances. 

- If you can’t afford a lawyer, you have a right to be represented at no cost by a public defender or other court-appointed lawyer. 