---
title: Know Your Rights
subtitle: Law Student Residents, Interns, & Law Clerks
author: Eric M. Fink
institute: Elon Law School 
date: 6 November 2025
date-format: "D MMMM YYYY"

format:
  metropolis-revealjs: 
    css: metropolis.css
    controls: true
    navigation-mode: vertical
    incremental: true
    slide-level: 4
    output-file: law-student-employment-revealjs.html

---

# Disclaimer

The information in this presentation is not intended to constitute legal advice and should not be relied upon in lieu of consultation with appropriate legal counsel.

# Employment Law

## Examples

- Wages & Hours
	- Fair Labor Standards Act 
	- State wage payment law
- Anti-Discrimination
	- Civil Rights Act of 1964, Title VII
	- ADA
	- Family & Medical Leave Act
- Health & Safety 
	- OSHA
	- Workers compensation 

### Coverage

Depends on legal status as an employee

- Some laws have additional conditions or exemptions

## Fair Labor Standards Act

### Internships: Primary Beneficiary Test

> [A]n employment relationship is not created when the tangible and intangible benefits provided to the intern are greater than the intern's contribution to the employer's operation. 

_Glatt v. Fox Searchlight Pictures_ (2d Cir. 2015)

### Primary Beneficiary Test

> The internship may provide a direct benefit to the employer so long as the intern receives identifiable educational or vocational benefits in return.

_Wang v. Hearst Corp._, 877 F.3d 69 (2d Cir. 2017)

### Primary Beneficiary Test: Factors 

- Extent to which the intern and employer clearly understand that there is no expectation of compensation. Any promise of compensation, express or implied, suggests that the intern is an employee—and vice versa.
- Extent to which the internship provides training similar to what would be given in an educational environment, including clinical and other hands-on training provided by educational institutions.
- _Extent to which the internship is tied to the intern’s formal education program by integrated coursework or receipt of academic credit_.
- _Extent to which the internship accommodates the intern’s academic commitments by corresponding to the academic calendar_.
- _Extent to which the internship’s duration is limited to the period in which the internship provides the intern with beneficial learning_.
- Extent to which the intern’s work complements, rather than displaces, the work of paid employees while providing significant educational benefits to the intern.
- Extent to which the intern and the employer understand that the internship is conducted without entitlement to a paid job at the conclusion of the internship.

### Primary Beneficiary Test

- Totality of circumstances
- No single factor is decisive

### Internships with Government and Non-Profits

- The FLSA expressly permits unpaid volunteers at public agencies.
- The Department of Labor has consistently interpreted the FLSA to permit unpaid volunteers with private non-profit organizations.
	- But only those engaged in the organization’s charitable work, not commercial activity. _Tony & Susan Alamo Foundation v. Secretary of Labor_ (US 1985)

## Anti-Discrimination

### Coverage

- Civil Rights Act of 1964, Title VII (Employees)
	- Race, color, religion, sex and national origin
- Civil Rights Act of 1964, Title VI (Students)
	- Race, color, national origin 
- Education Amendments of 1972, Title IX (Students)
	- Sex 
- ADA (Employees & Students)
	- Disability

### Unequal Terms and Conditions

- Disparate treatment
- Disparate impact

### Harassment

- Quid pro quo
- Hostile environment

### Harassment

> [Conduct] that is so severe, pervasive, and objectively offensive, and that so undermines and detracts from the victims’ educational experience, that the victims are effective denied equal access to an institution’s resources and opportunities.

_Davis v. Monroe County Board of Education_ (U.S. 1999) 

## Title IX

> No person in the United States shall, on the basis of sex, be excluded from participation in, be denied the benefits of, or be subjected to discrimination under any education program or activity receiving Federal financial assistance.

### "On the basis of sex"

Department of Education Interpretation

- 2024 Final Rule: "Discrimination on the basis of sex includes discrimination on the basis of sex stereotypes, sex characteristics, pregnancy or related conditions, sexual orientation, and gender identity."
	- Vacated on 1st Amendment and Spending Clause grounds. _State of Tennessee v. Cardona_ (January 9, 2025 E.D. Tenn.)
- 2025 "Dear Colleague" letter: "The department will return to enforcing Title IX protections on the basis of biological sex in schools and on campuses."

## Confidentiality & Conflicts of Interest

### Rules of Professional Conduct

Law students working as residents, interns, or employees in legal practice settings are subject to the Rules of Professional Conduct, including the the rules on confidentiality and conflicts of interest. 

### Duties Under Other Laws

- Common law or statutory duties of confidentiality and loyalty
- Non-disclosure agreements or policies